# Generated by Django 4.2 on 2023-04-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actorprofile",
            name="main_photo",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="additionalphoto",
            name="link",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="casting",
            name="photo",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="photo",
            field=models.ImageField(upload_to=""),
        ),
    ]
