# Generated by Django 4.2 on 2023-04-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0002_remove_actorprofile_photo_portfolio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actorprofile",
            name="experience",
        ),
        migrations.AddField(
            model_name="actorprofile",
            name="tag",
            field=models.ManyToManyField(to="core_app.tag"),
        ),
        migrations.DeleteModel(
            name="ActorExperience",
        ),
    ]
