# Generated by Django 4.2 on 2023-04-22 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0002_alter_actorprofile_main_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actorprofile",
            name="photo_portfolio",
        ),
        migrations.RemoveField(
            model_name="casting",
            name="additional_photo",
        ),
        migrations.DeleteModel(
            name="AdditionalPhoto",
        ),
    ]
