# Generated by Django 4.2 on 2023-05-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0003_remove_actorprofile_experience_actorprofile_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actorprofile",
            name="main_photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
