# Generated by Django 4.2 on 2023-05-01 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0004_alter_actorprofile_main_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actorprofile",
            name="video_business_card",
        ),
    ]
