# Generated by Django 4.2 on 2023-05-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0005_remove_actorprofile_video_business_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actorprofile",
            name="tag",
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="rating",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
