# Generated by Django 4.2 on 2023-05-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0008_alter_actorprofile_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="actorprofile",
            name="tag",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to="core_app.tag"),
            preserve_default=False,
        ),
    ]
