# Generated by Django 4.2 on 2023-05-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0009_actorprofile_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
