# Generated by Django 4.2 on 2023-05-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0010_alter_employerprofile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="rating",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
