# Generated by Django 4.2 on 2023-05-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0011_alter_employerprofile_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casting",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.RemoveField(
            model_name="casting",
            name="tag",
        ),
        migrations.AddField(
            model_name="casting",
            name="tag",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to="core_app.tag"),
            preserve_default=False,
        ),
    ]
