# Generated by Django 4.2 on 2023-05-08 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core_app", "0012_alter_casting_photo_remove_casting_tag_casting_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casting",
            name="casting_owner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
