# Generated by Django 4.2 on 2023-05-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0015_favoritesactor_favoritescasting_delete_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="response_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
