# Generated by Django 4.2 on 2023-05-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0016_alter_response_response_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casting",
            name="casting_owner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core_app.employerprofile"),
        ),
    ]
