# Generated by Django 4.2 on 2023-05-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0017_alter_casting_casting_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "casting_owner",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core_app.employerprofile"),
                ),
            ],
        ),
    ]
