# Generated by Django 4.2 on 2023-05-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0018_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
