# Generated by Django 4.2 on 2023-05-20 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core_app", "0019_notification_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="casting_owner",
        ),
        migrations.AddField(
            model_name="notification",
            name="owner",
            field=models.ForeignKey(
                default=int, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="favoritesactor",
            name="actor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core_app.actorprofile"),
        ),
        migrations.AlterField(
            model_name="favoritescasting",
            name="casting",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core_app.casting"),
        ),
    ]
