# Generated by Django 4.2 on 2023-05-24 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0021_alter_actorprofile_main_photo_alter_casting_photo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actorprofile",
            old_name="main_photo",
            new_name="photo",
        ),
    ]
