# Generated by Django 4.1.7 on 2023-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0022_rename_main_photo_actorprofile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actorprofile",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("not_choice", ""),
                    ("thin", "Худощавое"),
                    ("sports", "Спортивное"),
                    ("average", "Среднее"),
                    ("dense", "Плотное"),
                    ("fat", "Полное"),
                ],
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="education",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="eye_color",
            field=models.CharField(
                choices=[
                    ("not_choice", ""),
                    ("blue", "Голубые"),
                    ("gray", "Серые"),
                    ("green", "Зеленые"),
                    ("brown", "Карие"),
                ],
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="face_type",
            field=models.CharField(
                choices=[("not_choice", ""), ("oval", "Овальное"), ("round", "Круглое"), ("square", "Квадратное")],
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="figure_parameters",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="full_name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="hair_color",
            field=models.CharField(
                choices=[
                    ("not_choice", ""),
                    ("blonde", "Блонд"),
                    ("chestnut", "Каштан"),
                    ("dark_blonde", "Русые"),
                    ("dark", "Темные"),
                    ("redhead", "Рыжие"),
                ],
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="hair_length",
            field=models.CharField(
                choices=[("not_choice", ""), ("bald", "Лысый"), ("short", "Короткие"), ("long", "Длинные")],
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="language_proficiency",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="piercing",
            field=models.CharField(
                choices=[("not_choice", ""), ("exist", "Есть"), ("not_exist", "Нет")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="sex",
            field=models.CharField(
                choices=[("not_choice", ""), ("male", "Мужской"), ("female", "Женский")], max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="skills",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="skin_color",
            field=models.CharField(
                choices=[("not_choice", ""), ("white", "Белая"), ("swarthy", "Смуглая"), ("dark", "Темная")],
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="social_network",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="tattoo",
            field=models.CharField(
                choices=[("not_choice", ""), ("exist", "Есть"), ("not_exist", "Нет")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="actorprofile",
            name="voice_timbre",
            field=models.CharField(
                choices=[("not_choice", ""), ("high", "Высокий"), ("low", "Низкий")], max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="casting",
            name="actor_type_description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="casting",
            name="description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="casting",
            name="experience",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="casting",
            name="fee",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="casting",
            name="header",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="casting",
            name="sex",
            field=models.CharField(
                choices=[("not_choice", ""), ("male", "Мужской"), ("female", "Женский"), ("all", "Все")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="casting",
            name="social_network",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="approximate_location",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_specialization",
            field=models.CharField(
                choices=[
                    ("acting_agency", "Актерское агенство"),
                    ("film_company", "Кинокомпания"),
                    ("film_studio", "Киностудия"),
                    ("casting_agency", "Кастинг агенство"),
                    ("concert_agency", "Концертное агенство"),
                    ("casting_director", "Кастинг-директор"),
                    ("modeling_agency", "Модельное агенство"),
                    ("music_studio", "Музыкальная студия"),
                    ("selection", "Подбор кадров"),
                    ("producer", "Продюсер"),
                    ("director", "Режиссер"),
                    ("advertising_agency", "Рекламное агенство"),
                    ("tv_channel", "Телеканал"),
                    ("photo_studio", "Фото студия"),
                    ("other", "Другое"),
                ],
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="social_network",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
